let
  func = (InputTable as table, TopNRows as number, optional Delimiter as nullable text) as table =>
    let
      Delimiter = if Delimiter <> null then Delimiter else "#(lf)", 
      ToTables = Table.SplitAt(InputTable, TopNRows), 
      OldName = Table.ColumnNames(InputTable), 
      Transpose = Table.Transpose(ToTables{0}),
    TrColN = Table.ColumnNames(Transpose),
    ToText = Table.TransformColumnTypes(
        Transpose, 
        List.Transform(TrColN, each {_, type text})
      ),
    FillDown = Table.FillDown(ToText,TrColN), 
    ToColumns = Table.ToRows(FillDown), 
    CombineText = List.Transform(ToColumns, each Text.Combine(_, Delimiter))
in
    CombineText, 
  // Add documentation
  documentation = [
    Documentation.Name = " fn_CombineTopNRows ", 
    Documentation.Description = " Returns a Table with Combining X Number of Rows. ", 
    Documentation.LongDescription
      = " Returns a Table with Combining X Number of Rows and Promote them as header. ", 
    Documentation.Category = " Table ", 
    Documentation.Source
      = " https://www.biinsight.com/combining-x-number-of-rows-in-power-query-for-power-bi-excel-and-power-query-online/ ", 
    Documentation.Version = " 1.0 ", 
    Documentation.Author = " Muneer Marzouq, Mahmoud Bani Asadi, Soheil Bakhshi ", 
    Documentation.Examples = {
      [
        Description
          = " see this blogpost: https://www.biinsight.com/combining-x-number-of-rows-in-power-query-for-power-bi-excel-and-power-query-online/ ", 
        Code
          = " fn_CombineTopNRows(#table({""Column1"", ""Column2"", ""Column3""}, {{""TitleA"", ""TitleC"", ""Title1""}, {""TitleB"", ""TitleD"", ""Title2""}, {7, 8, 9}}), 2, "" "")", 
        Result = " #table({""TitleA TitleB"", ""TitleC TitleD"", ""Title1 Title2""}, {{7, 8, 9}}) "
      ]
    }
  ]
in
  Value.ReplaceType(func, Value.ReplaceMetadata(Value.Type(func), documentation))
