let fn_CreateDateTable = (Start as any, optional End as any, optional Culture as nullable text) as table =>
    let
        Culture=if Culture=null then "fa-IR" else Culture,
        StartDate= Date.FromText(try Date.ToText(Start,"yyy/MM/dd","en-EN") otherwise Start ,Culture),
        EndDate= if End=null then Date.FromText(Date.ToText(DateTime.Date(DateTime.LocalNow()),"yyy/MM/dd","en-EN"),Culture) else Date.FromText(try Date.ToText(End,"yyy/MM/dd","en-EN") otherwise End,Culture),
        DayCount = Duration.Days(Duration.From(EndDate - StartDate))+1,
        Source = List.Dates(StartDate,DayCount,#duration(1,0,0,0)),
        TableFromList = Table.FromList(Source, Splitter.SplitByNothing()),
        ChangedType = Table.TransformColumnTypes(TableFromList,{{"Column1", type date}}),
        RenamedColumns = Table.RenameColumns(ChangedType,{{"Column1", "Date"}}),
        InsertLocalDate = Table.AddColumn(RenamedColumns, "LocalDate", each Date.ToText([Date],"yyy/MM/dd",Culture)),
        DateNumber = Table.AddColumn(InsertLocalDate, "DateNumber", each Text.Remove([LocalDate],{"-","/"})),
        #"YYY/MM" = Table.AddColumn(DateNumber, "YYY/MM", each Text.Start([LocalDate],7),type text),
        InsertYear = Table.AddColumn(#"YYY/MM", "Year", each Number.FromText(Date.ToText([Date],"yyy",Culture))),
        InsertQuarter = Table.AddColumn(InsertYear, "QuarterOfYear", each Number.RoundUp(Number.FromText( Date.ToText([Date],"MM",Culture))/3,0)),
        InsertSeason = Table.AddColumn(InsertQuarter, "Season", each {"بهار","تابستان","پاییز","زمستان"}{[QuarterOfYear]-1}),
        InsertMonth = Table.AddColumn(InsertSeason, "MonthOfYear", each Number.FromText(Date.ToText([Date],"MM",Culture))),
        InsertDay = Table.AddColumn(InsertMonth, "DayOfMonth", each Number.FromText(Date.ToText([Date],"dd",Culture))),
        InsertMonthName = Table.AddColumn(InsertDay, "MonthName", each Date.ToText([Date], "MMMM", Culture), type text),
        InsertCalendarMonth = Table.AddColumn(InsertMonthName, "MonthInCalendar", each Date.ToText([Date],"MMM",Culture)&" "&Date.ToText([Date],"yyy",Culture)),
        InsertCalendarQtr = Table.AddColumn(InsertCalendarMonth, "QuarterInCalendar", each {"بهار","تابستان","پاییز","زمستان"}{[QuarterOfYear]-1} & "-" & Number.ToText([Year])),
        InsertDayWeek = Table.AddColumn(InsertCalendarQtr, "DayInWeek", each (Date.DayOfWeek([Date],Day.Saturday)+1)),
        InsertDayName = Table.AddColumn(InsertDayWeek, "DayOfWeekName", each Date.ToText([Date], "dddd", Culture), type text),
        DayofYear = Table.AddColumn(InsertDayName, "ShamsiDayOfYear", each if Date.DayOfYear([Date])>=80 then Date.DayOfYear([Date])-79 else Date.DayOfYear([Date])+286,Int64.Type),
        InsertWeekEnding = Table.AddColumn(DayofYear, "WeekEnding", each Date.ToText(Date.EndOfWeek([Date],Day.Saturday),"yyy/MM/dd",Culture)),
        RenameColumns = Table.RenameColumns(InsertWeekEnding,{{"Date", "تاریخ میلادی"}, {"LocalDate", "تاریخ شمسی"}, {"DateNumber", "تاریخ عددی"}, {"YYY/MM", "سال و ماه"}, {"Year", "سال"}, {"QuarterOfYear", "شماره فصل"}, {"Season", "فصل"}, {"MonthOfYear", "شماره ماه"}, {"DayOfMonth", "روز"}, {"MonthName", "نام ماه"}, {"MonthInCalendar", "نام ماه و سال"}, {"QuarterInCalendar", "فصل و سال"}, {"DayInWeek", "روز هفته"}, {"DayOfWeekName", "نام روز هفته"}, {"ShamsiDayOfYear", "شماره روز سال"}, {"WeekEnding", "تاریخ پایان هفته"}})
    in
        RenameColumns,
FunctionType = type function
        (
            Start as 
            (type date meta
                [
                Documentation.FieldCaption = "Starting local date",
                Documentation.FieldDescription = "Put a date based on culture in third field, Persian date is default",
                Documentation.SampleValues = {"1367/01/25"}
                ]
            ),
            optional End as 
            (type date meta
                [
                Documentation.FieldCaption = "Ending local date",
                Documentation.FieldDescription = "Put a date based on culture in third field, Persian date is default and if skip blank, Current Persian date is default",
                Documentation.SampleValues = {"1400/01/01"}
                ]
            ),
            optional Culture as 
            (type text meta
                [
                Documentation.FieldCaption = "Region code to create dimDate",
                Documentation.FieldDescription = "Put a region code like ""fa-IR"" as text",
                Documentation.AllowedValues = {"fa-IR", "en-US", "en-GB", "fr-FR", "de-DE", "es-ES", "it-IT", "zh-CN", "ar-SA", "he-IL", "hi-IN", "ja-JP", "th-TH"}
                ]
            )
        ) as table 
        meta
        [
            Documentation.Name = "fn_CreateDateTable",
            Documentation.Description = "Create dimDate table for local date - default is Persian ",
            Documentation.Version = " 1.0 ",
            Documentation.Category = " Table ",
            Documentation.Author = " Mahmoud Bani Asadi ",
            Documentation.Source = " https://www.arshad-hesabdar.ir ",
            Documentation.Examples = {[Description =  " see this blog post: https://www.vahiddm.com/post/shamsi-date-table-powerbi",
        Code = " fn_CreateDateTable(""1367/01/25"",""1401/01/01"",""fa-IR"")",
        Result = " DimDateTable "]}       
        ]
in
    Value.ReplaceType(fn_CreateDateTable, FunctionType)
